version: "2"

services:

  ai-core:
    container_name: ai-core
    image: jayjohnson/ai-core:latest
    hostname: ai-core
    network_mode: "host"
    environment:
      - JUPYTER_PASS=admin
      - SHARED_DIR=/opt/data
      - BROKER_URL=redis://0.0.0.0:6379/6
    ports:
      - "8888:8888"
      - "8080:8080"
      - "8889:8889"
      - "6006:6006"
    # volumes:
    # for sharing inside the container
    # - ./data:/data
    # - ./jupyter/start-container.sh:/home/runner/.jupyter/start-container.sh
    # - ./notebooks:/home/runner/notebooks
    # - ./jupyter:/home/runner/.jupyter
    entrypoint: "/home/runner/.jupyter/start-container.sh"
    # start another process instead:
    # entrypoint: "/opt/antinex-core/run-antinex-core.sh"
    # entrypoint: "jupyter notebook --ip=* --port=8888 \
    #              --no-browser \
    #              --config=/home/runner/.jupyter/jupyter_notebook_config.py \
    #              --notebook-dir=/home/runner/notebooks --allow-root"

  # Redis
  redis:
    container_name: "redis"
    hostname: redis
    image: redis:4.0.5-alpine
    network_mode: "host"
    ports:
      - "6379:6379"
